// apps/portal/src/app/layout/AppMenu.tsx
/* eslint-disable @next/next/no-img-element */

import React, { useContext } from 'react';
import AppMenuitem from './AppMenuitem';
import { LayoutContext } from './context/layoutcontext';
import { MenuProvider } from './context/menucontext';
import Link from 'next/link';
import { AppMenuItem } from '../types';

const AppMenu = () => {
  const { layoutConfig } = useContext(LayoutContext);

  const model: AppMenuItem[] = [
    {
      label: 'Home',
      items: [{ label: 'Dashboard', icon: 'pi pi-fw pi-home', to: '/' }]
    },
    {
      label: 'UI Components',
      items: [
        { label: 'Form Layout', icon: 'pi pi-fw pi-id-card', to: '/uikit/formlayout' },
        { label: 'Input', icon: 'pi pi-fw pi-check-square', to: '/uikit/input' },
        { label: 'Float Label', icon: 'pi pi-fw pi-bookmark', to: '/uikit/floatlabel' },
        { label: 'Invalid State', icon: 'pi pi-fw pi-exclamation-circle', to: '/uikit/invalidstate' },
        { label: 'Button', icon: 'pi pi-fw pi-mobile', to: '/uikit/button', class: 'rotated-icon' },
        { label: 'Table', icon: 'pi pi-fw pi-table', to: '/uikit/table' },
        { label: 'List', icon: 'pi pi-fw pi-list', to: '/uikit/list' },
        { label: 'Tree', icon: 'pi pi-fw pi-share-alt', to: '/uikit/tree' },
        { label: 'Panel', icon: 'pi pi-fw pi-tablet', to: '/uikit/panel' },
        { label: 'Overlay', icon: 'pi pi-fw pi-clone', to: '/uikit/overlay' },
        { label: 'Media', icon: 'pi pi-fw pi-image', to: '/uikit/media' },
        { label: 'Menu', icon: 'pi pi-fw pi-bars', to: '/uikit/menu', preventExact: true },
        { label: 'Message', icon: 'pi pi-fw pi-comment', to: '/uikit/message' },
        { label: 'File', icon: 'pi pi-fw pi-file', to: '/uikit/file' },
        { label: 'Chart', icon: 'pi pi-fw pi-chart-bar', to: '/uikit/charts' },
        { label: 'Misc', icon: 'pi pi-fw pi-circle', to: '/uikit/misc' }
      ]
    },
    {
      label: 'Prime Blocks',
      items: [
        { label: 'Free Blocks', icon: 'pi pi-fw pi-eye', to: '/blocks', badge: 'NEW' },
        { label: 'All Blocks', icon: 'pi pi-fw pi-globe', url: 'https://blocks.primereact.org', target: '_blank' }
      ]
    },
    {
      label: 'Utilities',
      items: [
        { label: 'PrimeIcons', icon: 'pi pi-fw pi-prime', to: '/utilities/icons' },
        { label: 'PrimeFlex', icon: 'pi pi-fw pi-desktop', url: 'https://primeflex.org/', target: '_blank' }
      ]
    },
    {
      label: 'Pages',
      icon: 'pi pi-fw pi-briefcase',
      to: '/pages',
      items: [
        {
          label: 'Landing',
          icon: 'pi pi-fw pi-globe',
          to: '/landing'
        },
        {
          label: 'Auth',
          icon: 'pi pi-fw pi-user',
          items: [
            {
              label: 'Login',
              icon: 'pi pi-fw pi-sign-in',
              to: '/auth/login'
            },
            {
              label: 'Error',
              icon: 'pi pi-fw pi-times-circle',
              to: '/auth/error'
            },
            {
              label: 'Access Denied',
              icon: 'pi pi-fw pi-lock',
              to: '/auth/access'
            }
          ]
        },
        {
          label: 'Crud',
          icon: 'pi pi-fw pi-pencil',
          to: '/pages/crud'
        },
        {
          label: 'Timeline',
          icon: 'pi pi-fw pi-calendar',
          to: '/pages/timeline'
        },
        {
          label: 'Not Found',
          icon: 'pi pi-fw pi-exclamation-circle',
          to: '/pages/notfound'
        },
        {
          label: 'Empty',
          icon: 'pi pi-fw pi-circle-off',
          to: '/pages/empty'
        }
      ]
    },
    {
      label: 'Hierarchy',
      items: [
        {
          label: 'Submenu 1',
          icon: 'pi pi-fw pi-bookmark',
          items: [
            {
              label: 'Submenu 1.1',
              icon: 'pi pi-fw pi-bookmark',
              items: [
                { label: 'Submenu 1.1.1', icon: 'pi pi-fw pi-bookmark' },
                { label: 'Submenu 1.1.2', icon: 'pi pi-fw pi-bookmark' },
                { label: 'Submenu 1.1.3', icon: 'pi pi-fw pi-bookmark' }
              ]
            },
            {
              label: 'Submenu 1.2',
              icon: 'pi pi-fw pi-bookmark',
              items: [{ label: 'Submenu 1.2.1', icon: 'pi pi-fw pi-bookmark' }]
            }
          ]
        },
        {
          label: 'Submenu 2',
          icon: 'pi pi-fw pi-bookmark',
          items: [
            {
              label: 'Submenu 2.1',
              icon: 'pi pi-fw pi-bookmark',
              items: [
                { label: 'Submenu 2.1.1', icon: 'pi pi-fw pi-bookmark' },
                { label: 'Submenu 2.1.2', icon: 'pi pi-fw pi-bookmark' }
              ]
            },
            {
              label: 'Submenu 2.2',
              icon: 'pi pi-fw pi-bookmark',
              items: [{ label: 'Submenu 2.2.1', icon: 'pi pi-fw pi-bookmark' }]
            }
          ]
        }
      ]
    },
    {
      label: 'Get Started',
      items: [
        {
          label: 'Documentation',
          icon: 'pi pi-fw pi-question',
          to: '/documentation'
        },
        {
          label: 'Figma',
          url: 'https://www.dropbox.com/scl/fi/bhfwymnk8wu0g5530ceas/sakai-2023.fig?rlkey=u0c8n6xgn44db9t4zkd1brr3l&dl=0',
          icon: 'pi pi-fw pi-pencil',
          target: '_blank'
        },
        {
          label: 'View Source',
          icon: 'pi pi-fw pi-search',
          url: 'https://github.com/primefaces/sakai-react',
          target: '_blank'
        }
      ]
    }
  ];

  return (
    <MenuProvider>
      <ul className="layout-menu">
        {model.map((item, i) => {
          return !item?.seperator ? <AppMenuitem item={item} root={true} index={i} key={item.label} /> : <li className="menu-separator"></li>;
        })}

        <Link href="https://blocks.primereact.org" target="_blank" style={{ cursor: 'pointer' }}>
          <img alt="Prime Blocks" className="w-full mt-3" src={`/layout/images/banner-primeblocks${layoutConfig.colorScheme === 'light' ? '' : '-dark'}.png`} />
        </Link>
      </ul>
    </MenuProvider>
  );
};

export default AppMenu;

// apps/admin/src/app/layout/components/app.menu.component.ts
import { OnInit } from '@angular/core';
import { Component } from '@angular/core';
import { LayoutService } from '../service/app.layout.service';

@Component({
    selector: 'app-menu',
    templateUrl: './app.menu.component.html'
})
export class AppMenuComponent implements OnInit {

    model: any[] = [];

    constructor(public layoutService: LayoutService) { }

    ngOnInit() {
        this.model = [
            {
                label: 'Home',
                items: [
                    {
                        label: 'Dashboard', icon: 'assets/images/icons/dashboard-colored.png', height: '25', padding: 'pt-2 pl-2', routerLink: ['/modules']
                    }
                ]
            },
            {
                label: 'Courses',
                items: [
                    // { label: 'Sample', icon: 'assets/images/icons/layers-2.png', height: '25', padding: 'pt-2 pl-2', routerLink: ['/modules/course-schedule/list'] },
                    {
                        label: 'Courses', height: '25', class: 'no-background', padding: 'pt-2 pl-2', routerLink: ['/modules/course-schedule/list'],
                        items: [
                            {
                                label: 'Explore', icon: 'assets/images/icons/my-courses.png', height: '25', padding: 'pt-2 pl-2', routerLink: ['/modules/course-schedule/list'],
                            },
                            {
                                label: 'My Courses', icon: 'assets/images/icons/my_courses.png', height: '25', padding: 'pt-2 pl-2', routerLink: ['/modules/course-schedule/subscriptions'],
                            },
                        ]
                    }
                    // { label: 'Input', icon: 'assets/images/icons/layers-2.png', height: '25', padding: 'pt-2 pl-2', routerLink: ['/uikit/input'] },
                    // { label: 'Float Label', icon: 'assets/images/icons/layers-2.png', height: '25', padding: 'pt-2 pl-2', routerLink: ['/uikit/floatlabel'] },
                    // { label: 'Invalid State', icon: 'assets/images/icons/layers-2.png', height: '25', padding: 'pt-2 pl-2', routerLink: ['/uikit/invalidstate'] },
                    // { label: 'Button', icon: 'assets/images/icons/layers-2.png', height: '25', padding: 'pt-2 pl-2', routerLink: ['/uikit/button'] },
                    // { label: 'Table', icon: 'assets/images/icons/layers-2.png', height: '25', padding: 'pt-2 pl-2', routerLink: ['/uikit/table'] },
                    // { label: 'List', icon: 'assets/images/icons/layers-2.png', height: '25', padding: 'pt-2 pl-2', routerLink: ['/uikit/list'] },
                    // { label: 'Tree', icon: 'assets/images/icons/layers-2.png', height: '25', padding: 'pt-2 pl-2', routerLink: ['/uikit/tree'] },
                    // { label: 'Panel', icon: 'assets/images/icons/layers-2.png', height: '25', padding: 'pt-2 pl-2', routerLink: ['/uikit/panel'] },
                    // { label: 'Overlay', icon: 'assets/images/icons/layers-2.png', height: '25', padding: 'pt-2 pl-2', routerLink: ['/uikit/overlay'] },
                    // { label: 'Media', icon: 'assets/images/icons/layers-2.png', height: '25', padding: 'pt-2 pl-2', routerLink: ['/uikit/media'] },
                    // { label: 'Menu', icon: 'assets/images/icons/layers-2.png', height: '25', padding: 'pt-2 pl-2', routerLink: ['/uikit/menu'], routerLinkActiveOptions: { paths: 'subset', queryParams: 'ignored', matrixParams: 'ignored', fragment: 'ignored' } },
                    // { label: 'Message', icon: 'assets/images/icons/layers-2.png', height: '25', padding: 'pt-2 pl-2', routerLink: ['/uikit/message'] },
                    // { label: 'File', icon: 'assets/images/icons/layers-2.png', height: '25', padding: 'pt-2 pl-2', routerLink: ['/uikit/file'] },
                    // { label: 'Chart', icon: 'assets/images/icons/layers-2.png', height: '25', padding: 'pt-2 pl-2', routerLink: ['/uikit/charts'] },
                    // { label: 'Misc', icon: 'assets/images/icons/layers-2.png', height: '25', padding: 'pt-2 pl-2', routerLink: ['/uikit/misc'] }
                ]
            },
            // {
            //     label: 'Prime Blocks',
            //     items: [
            //         { label: 'Free Blocks', icon: 'assets/images/icons/layers-2.png', height: '25', padding: 'pt-2 pl-2', routerLink: ['/blocks'], badge: 'NEW' },
            //         { label: 'All Blocks', icon: 'assets/images/icons/layers-2.png', height: '25', padding: 'pt-2 pl-2', url: ['https://www.primefaces.org/primeblocks-ng'], target: '_blank' },
            //     ]
            // },
            // {
            //     label: 'Utilities',
            //     items: [
            //         { label: 'PrimeIcons', icon: 'assets/images/icons/layers-2.png', height: '25', padding: 'pt-2 pl-2', routerLink: ['/utilities/icons'] },
            //         { label: 'PrimeFlex', icon: 'assets/images/icons/layers-2.png', height: '25', padding: 'pt-2 pl-2', url: ['https://www.primefaces.org/primeflex/'], target: '_blank' },
            //     ]
            // },
            // {
            //     label: 'Pages',
            //     icon: 'pi pi-fw pi-briefcase',
            //     items: [
            //         {
            //             label: 'Landing', icon: 'assets/images/icons/layers-2.png', height: '25', padding: 'pt-2 pl-2', routerLink: ['/landing']
            //         },
            //         {
            //             label: 'Auth',
            //             icon: 'pi pi-fw pi-user',
            //             items: [
            //                 {
            //                     label: 'Login', icon: 'assets/images/icons/layers-2.png', height: '25', padding: 'pt-2 pl-2', routerLink: ['/auth/login']
            //                 },
            //                 {
            //                     label: 'Error', icon: 'assets/images/icons/layers-2.png', height: '25', padding: 'pt-2 pl-2', routerLink: ['/auth/error']
            //                 },
            //                 {
            //                     label: 'Access Denied', routerLink: ['/auth/access']
            //                 }
            //             ]
            //         },
            //         {
            //             label: 'Crud', icon: 'assets/images/icons/layers-2.png', height: '25', padding: 'pt-2 pl-2', routerLink: ['/pages/crud']
            //         },
            //         {
            //             label: 'Timeline', icon: 'assets/images/icons/layers-2.png', height: '25', padding: 'pt-2 pl-2', routerLink: ['/pages/timeline']
            //         },
            //         {
            //             label: 'Not Found', icon: 'assets/images/icons/layers-2.png', height: '25', padding: 'pt-2 pl-2', routerLink: ['/notfound']
            //         },
            //         {
            //             label: 'Empty', icon: 'assets/images/icons/layers-2.png', height: '25', padding: 'pt-2 pl-2', routerLink: ['/pages/empty']
            //         },
            //     ]
            // },
            // {
            //     label: 'Hierarchy',
            //     items: [
            //         {
            //             label: 'Submenu 1', icon: 'assets/images/icons/layers-2.png', height: '25', padding: 'pt-2 pl-2',
            //             items: [
            //                 {
            //                     label: 'Submenu 1.1', icon: 'pi pi-fw pi-bookmark',
            //                     items: [
            //                         { label: 'Submenu 1.1.1', icon: 'assets/images/icons/layers-2.png', height: '25', padding: 'pt-2 pl-2', },
            //                         { label: 'Submenu 1.1.2', icon: 'assets/images/icons/layers-2.png', height: '25', padding: 'pt-2 pl-2' },
            //                         { label: 'Submenu 1.1.3', icon: 'assets/images/icons/layers-2.png', height: '25', padding: 'pt-2 pl-2' },
            //                     ]
            //                 },
            //                 {
            //                     label: 'Submenu 1.2', icon: 'assets/images/icons/layers-2.png', height: '25', padding: 'pt-2 pl-2',
            //                     items: [
            //                         { label: 'Submenu 1.2.1', icon: 'assets/images/icons/layers-2.png', height: '25', padding: 'pt-2 pl-2' }
            //                     ]
            //                 },
            //             ]
            //         },
            //         {
            //             label: 'Submenu 2', icon: 'assets/images/icons/layers-2.png', height: '25', padding: 'pt-2 pl-2',
            //             items: [
            //                 {
            //                     label: 'Submenu 2.1', icon: 'assets/images/icons/layers-2.png', height: '25', padding: 'pt-2 pl-2',
            //                     items: [
            //                         { label: 'Submenu 2.1.1', icon: 'assets/images/icons/layers-2.png', height: '25', padding: 'pt-2 pl-2' },
            //                         { label: 'Submenu 2.1.2', icon: 'assets/images/icons/layers-2.png', height: '25', padding: 'pt-2 pl-2' },
            //                     ]
            //                 },
            //                 {
            //                     label: 'Submenu 2.2', icon: 'assets/images/icons/layers-2.png', height: '25', padding: 'pt-2 pl-2',
            //                     items: [
            //                         { label: 'Submenu 2.2.1', icon: 'assets/images/icons/layers-2.png', height: '25', padding: 'pt-2 pl-2' },
            //                     ]
            //                 },
            //             ]
            //         }
            //     ]
            // },
            // {
            //     label: 'Get Started',
            //     items: [
            //         {
            //             label: 'Documentation', icon: 'assets/images/icons/layers-2.png', height: '25', padding: 'pt-2 pl-2', routerLink: ['/documentation']
            //         },
            //         {
            //             label: 'View Source', icon: 'assets/images/icons/layers-2.png', height: '25', padding: 'pt-2 pl-2', url: ['https://github.com/primefaces/sakai-ng'], target: '_blank'
            //         }
            //     ]
            // }
        ];
    }
}

<ul class="layout-menu">
    <ng-container *ngFor="let item of model; let i = index;">
        <li class="w-full" app-menuitem *ngIf="!item.separator" [item]="item" [index]="i" [root]="true"></li>
        <li class="w-full" *ngIf="item.separator" class="menu-separator"></li>
    </ng-container>
    <!-- <li>
        <a href="https://www.primefaces.org/primeblocks-ng/#/">
            <img src="assets/layout/images/{{layoutService.config().colorScheme === 'light' ? 'banner-primeblocks' : 'banner-primeblocks-dark'}}.png" alt="Prime Blocks" class="w-full mt-3"/>
        </a>
    </li> -->
</ul>
